### PR TITLE
blackfire::php has a manage parameter, which is not respected

### PR DESCRIPTION
**Pull request by Schnitzel**
the attached patch fixes that.

### CODE REVIEW

**Comment by twardnw** [comment]
looks good to me @Schnitzel

**Comment by dasrecht** [comment]
looks good :) go for it

**Comment by s12v** [comment]
👍

**Comment by s12v** [comment]
thank you @Schnitzel

**Comment by Schnitzel** [comment]
@s12v 
thank you! Could I also ask for a new release? :)

**Comment by s12v** [comment]
@Schnitzel, sure, uploaded 1.5.2

**Pull request merged**
